/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package urnaeletronica;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCELO
 */
public class CadastroEleitor extends javax.swing.JFrame {

        String nome = "";
        String nascimento = "";
        String inscricao = "";
        int zona = 0;
        int secao = 0;
        String emissao = "";
        String uf = "";
        String municipio = "";
        String pai = "";
        String mae = "";
    
    public CadastroEleitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNL_ELEITOR = new javax.swing.JPanel();
        LBL_BRASAO = new javax.swing.JLabel();
        LBL_NOME = new javax.swing.JLabel();
        LBL_NASCIMENTO = new javax.swing.JLabel();
        LBL_INSCRICAO = new javax.swing.JLabel();
        LBL_ZONA = new javax.swing.JLabel();
        LBL_SECAO = new javax.swing.JLabel();
        TXT_SECAO = new javax.swing.JTextField();
        LBL_EMISSAO = new javax.swing.JLabel();
        TXT_NOME = new javax.swing.JTextField();
        TXT_INSCRICAO = new javax.swing.JTextField();
        TXT_NASCIMENTO = new javax.swing.JFormattedTextField();
        TXT_EMISSAO = new javax.swing.JFormattedTextField();
        TXT_ZONA = new javax.swing.JTextField();
        LBL_UF = new javax.swing.JLabel();
        CBB_UF = new javax.swing.JComboBox<>();
        LBL_MUNICIPIO = new javax.swing.JLabel();
        CBB_MUNICIPIO = new javax.swing.JComboBox<>();
        LBL_NOME_PAI = new javax.swing.JLabel();
        TXT_NOME_PAI = new javax.swing.JTextField();
        LBL_NOME_MAE = new javax.swing.JLabel();
        TXT_NOME_MAE = new javax.swing.JTextField();
        BTN_VOTAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PNL_ELEITOR.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ELEITOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        PNL_ELEITOR.setPreferredSize(new java.awt.Dimension(795, 518));

        LBL_BRASAO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/urnaeletronica/imagens/BrasaoJusticaEleitoral.png"))); // NOI18N
        LBL_BRASAO.setMaximumSize(new java.awt.Dimension(79, 74));
        LBL_BRASAO.setMinimumSize(new java.awt.Dimension(79, 74));
        LBL_BRASAO.setPreferredSize(new java.awt.Dimension(79, 74));

        LBL_NOME.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBL_NOME.setText("NOME DO(A) ELEITOR(A):");

        LBL_NASCIMENTO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBL_NASCIMENTO.setText("DATA DE NASCIMENTO:");

        LBL_INSCRICAO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBL_INSCRICAO.setText("NÚMERO DE INSCRIÇÃO:");

        LBL_ZONA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBL_ZONA.setText("ZONA:");

        LBL_SECAO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBL_SECAO.setText("SEÇÃO:");

        LBL_EMISSAO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBL_EMISSAO.setText("DATA DE EMISSÃO:");

        try {
            TXT_NASCIMENTO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## / ## / ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TXT_NASCIMENTO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        try {
            TXT_EMISSAO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## / ## / ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TXT_EMISSAO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LBL_UF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBL_UF.setText("UF:");

        CBB_UF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione UF", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        CBB_UF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBB_UFActionPerformed(evt);
            }
        });

        LBL_MUNICIPIO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBL_MUNICIPIO.setText("MUNICÍPIO:");

        LBL_NOME_PAI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBL_NOME_PAI.setText("NOME DO PAI:");

        LBL_NOME_MAE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBL_NOME_MAE.setText("NOME DA MÃE:");

        BTN_VOTAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_VOTAR.setText("VOTAR");
        BTN_VOTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_VOTARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNL_ELEITORLayout = new javax.swing.GroupLayout(PNL_ELEITOR);
        PNL_ELEITOR.setLayout(PNL_ELEITORLayout);
        PNL_ELEITORLayout.setHorizontalGroup(
            PNL_ELEITORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_ELEITORLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LBL_BRASAO, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(PNL_ELEITORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LBL_NOME_MAE)
                    .addComponent(LBL_NOME_PAI)
                    .addComponent(LBL_MUNICIPIO)
                    .addComponent(LBL_UF)
                    .addComponent(LBL_EMISSAO)
                    .addComponent(LBL_NOME)
                    .addComponent(LBL_NASCIMENTO)
                    .addGroup(PNL_ELEITORLayout.createSequentialGroup()
                        .addComponent(LBL_ZONA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXT_ZONA, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBL_SECAO))
                    .addComponent(LBL_INSCRICAO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNL_ELEITORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXT_SECAO, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_NOME, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_NASCIMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBB_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_EMISSAO, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PNL_ELEITORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CBB_MUNICIPIO, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TXT_INSCRICAO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TXT_NOME_PAI, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_NOME_MAE, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_ELEITORLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_VOTAR)
                .addContainerGap())
        );
        PNL_ELEITORLayout.setVerticalGroup(
            PNL_ELEITORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_ELEITORLayout.createSequentialGroup()
                .addGroup(PNL_ELEITORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_ELEITORLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBL_BRASAO, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PNL_ELEITORLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PNL_ELEITORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_NOME)
                            .addComponent(TXT_NOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PNL_ELEITORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_NASCIMENTO)
                            .addComponent(TXT_NASCIMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PNL_ELEITORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_INSCRICAO)
                            .addComponent(TXT_INSCRICAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PNL_ELEITORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_SECAO)
                            .addComponent(TXT_SECAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_ZONA)
                            .addComponent(TXT_ZONA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PNL_ELEITORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_EMISSAO)
                            .addComponent(TXT_EMISSAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PNL_ELEITORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_UF)
                            .addComponent(CBB_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PNL_ELEITORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_MUNICIPIO)
                            .addComponent(CBB_MUNICIPIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PNL_ELEITORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_NOME_PAI)
                            .addComponent(TXT_NOME_PAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_ELEITORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_NOME_MAE)
                            .addComponent(TXT_NOME_MAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(BTN_VOTAR)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(PNL_ELEITOR, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PNL_ELEITOR, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CBB_UFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBB_UFActionPerformed
        CBB_MUNICIPIO.removeAllItems();
        uf = (String) CBB_UF.getSelectedItem();
        
        String sql = "select * from municipio where MUN_UF_SIGLA = ?";

        String url = "jdbc:mysql://127.0.0.1:3306/eleicao";
        String user = "root";
        String senha = "shieldcorrupted";

        try{
            Connection conexao = DriverManager.getConnection(url, user, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);
            
            comando.setString(1, uf);
            ResultSet busca = comando.executeQuery();

            while(busca.next()==true){
                municipio = busca.getString("MUN_CIDADE");
                CBB_MUNICIPIO.addItem(municipio);
            }

            busca.close();
            comando.close();
            conexao.close();

        }catch(SQLException erro){
            erro.printStackTrace();
        }
    }//GEN-LAST:event_CBB_UFActionPerformed

    private void BTN_VOTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_VOTARActionPerformed
        nome = TXT_NOME.getText();
        nascimento = TXT_NASCIMENTO.getText();
        inscricao = TXT_INSCRICAO.getText();
        zona = Integer.parseInt(TXT_ZONA.getText());
        secao = Integer.parseInt(TXT_SECAO.getText());
        emissao = TXT_EMISSAO.getText();
        uf = (String) CBB_UF.getSelectedItem();
        municipio = (String) CBB_MUNICIPIO.getSelectedItem();
        pai = TXT_NOME_PAI.getText();
        mae = TXT_NOME_MAE.getText();

        String sql = "insert eleitor values(?,?,?,?,?,?,?,?,?,?)";

        String url = "jdbc:mysql://127.0.0.1:3306/eleicao";
        String user = "root";
        String senha = "shieldcorrupted";

        try{
            Connection conexao = DriverManager.getConnection(url, user, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            comando.setString(1, inscricao);
            comando.setString(2, nome);
            comando.setString(3, nascimento);
            comando.setInt(4, zona);
            comando.setInt(5, secao);
            comando.setString(6, emissao);
            comando.setString(7, municipio);
            comando.setString(8, uf);
            comando.setString(9, pai);
            comando.setString(10, mae);
            comando.executeUpdate();

            comando.close();
            conexao.close();

            JOptionPane.showMessageDialog(null, "ELEITOR REGISTRADO!");
            
            TelaVotacao tela = new TelaVotacao();
            tela.setVisible(true);
            dispose();

        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "NÃO FOI POSSÍVEL REGISTRAR O ELEITOR!"
                + "\nVERIFIQUE SE PREENCHEU TODOS OS CAMPOS CORRETAMENTE!");
            erro.printStackTrace();
        }
    }//GEN-LAST:event_BTN_VOTARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroEleitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_VOTAR;
    private javax.swing.JComboBox<String> CBB_MUNICIPIO;
    private javax.swing.JComboBox<String> CBB_UF;
    private javax.swing.JLabel LBL_BRASAO;
    private javax.swing.JLabel LBL_EMISSAO;
    private javax.swing.JLabel LBL_INSCRICAO;
    private javax.swing.JLabel LBL_MUNICIPIO;
    private javax.swing.JLabel LBL_NASCIMENTO;
    private javax.swing.JLabel LBL_NOME;
    private javax.swing.JLabel LBL_NOME_MAE;
    private javax.swing.JLabel LBL_NOME_PAI;
    private javax.swing.JLabel LBL_SECAO;
    private javax.swing.JLabel LBL_UF;
    private javax.swing.JLabel LBL_ZONA;
    private javax.swing.JPanel PNL_ELEITOR;
    private javax.swing.JFormattedTextField TXT_EMISSAO;
    private javax.swing.JTextField TXT_INSCRICAO;
    private javax.swing.JFormattedTextField TXT_NASCIMENTO;
    private javax.swing.JTextField TXT_NOME;
    private javax.swing.JTextField TXT_NOME_MAE;
    private javax.swing.JTextField TXT_NOME_PAI;
    private javax.swing.JTextField TXT_SECAO;
    private javax.swing.JTextField TXT_ZONA;
    // End of variables declaration//GEN-END:variables
}
