/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package urnaeletronica;

/**
 *
 * @author MARCELO
 */
public class LoginUrna extends javax.swing.JFrame {

    /**
     * Creates new form LoginUrna
     */
    public LoginUrna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNL_TELA = new javax.swing.JPanel();
        LBL_EMAIL = new javax.swing.JLabel();
        LBL_SENHA = new javax.swing.JLabel();
        TXT_EMAIL = new javax.swing.JTextField();
        PSW_SENHA = new javax.swing.JPasswordField();
        BTN_LOGIN = new javax.swing.JButton();
        PNL_DESCRICAO = new javax.swing.JPanel();
        BTN_AJUDA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PNL_TELA.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        LBL_EMAIL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBL_EMAIL.setText("EMAIL:");

        LBL_SENHA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBL_SENHA.setText("SENHA:");

        BTN_LOGIN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_LOGIN.setText("LOGIN");

        PNL_DESCRICAO.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout PNL_DESCRICAOLayout = new javax.swing.GroupLayout(PNL_DESCRICAO);
        PNL_DESCRICAO.setLayout(PNL_DESCRICAOLayout);
        PNL_DESCRICAOLayout.setHorizontalGroup(
            PNL_DESCRICAOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );
        PNL_DESCRICAOLayout.setVerticalGroup(
            PNL_DESCRICAOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BTN_AJUDA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTN_AJUDA.setForeground(new java.awt.Color(255, 0, 0));
        BTN_AJUDA.setText("?");

        javax.swing.GroupLayout PNL_TELALayout = new javax.swing.GroupLayout(PNL_TELA);
        PNL_TELA.setLayout(PNL_TELALayout);
        PNL_TELALayout.setHorizontalGroup(
            PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_TELALayout.createSequentialGroup()
                .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_TELALayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_TELALayout.createSequentialGroup()
                                .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LBL_SENHA)
                                    .addComponent(LBL_EMAIL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXT_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(BTN_LOGIN)
                                        .addComponent(PSW_SENHA, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(PNL_DESCRICAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_TELALayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BTN_AJUDA)))
                .addContainerGap())
        );
        PNL_TELALayout.setVerticalGroup(
            PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_TELALayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(PNL_DESCRICAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_EMAIL)
                    .addComponent(TXT_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_SENHA)
                    .addComponent(PSW_SENHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(BTN_LOGIN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(BTN_AJUDA)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNL_TELA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNL_TELA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUrna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_AJUDA;
    private javax.swing.JButton BTN_LOGIN;
    private javax.swing.JLabel LBL_EMAIL;
    private javax.swing.JLabel LBL_SENHA;
    private javax.swing.JPanel PNL_DESCRICAO;
    private javax.swing.JPanel PNL_TELA;
    private javax.swing.JPasswordField PSW_SENHA;
    private javax.swing.JTextField TXT_EMAIL;
    // End of variables declaration//GEN-END:variables
}
