/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package urnaeletronica;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author MARCELO
 */
public class LoginUrna extends javax.swing.JFrame {

    /**
     * Creates new form LoginUrna
     */
    public LoginUrna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBL_BRASAO = new javax.swing.JLabel();
        PNL_TELA = new javax.swing.JPanel();
        PNL_DESCRICAO = new javax.swing.JPanel();
        LBL_EMAIL = new javax.swing.JLabel();
        TXT_EMAIL = new javax.swing.JTextField();
        LBL_SENHA = new javax.swing.JLabel();
        PSW_SENHA = new javax.swing.JPasswordField();
        BTN_LOGIN = new javax.swing.JButton();
        LBL_BRASAO1 = new javax.swing.JLabel();
        BTN_AJUDA = new javax.swing.JButton();

        LBL_BRASAO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/urnaeletronica/imagens/BrasaoJusticaEleitoral.png"))); // NOI18N
        LBL_BRASAO.setMaximumSize(new java.awt.Dimension(79, 74));
        LBL_BRASAO.setMinimumSize(new java.awt.Dimension(79, 74));
        LBL_BRASAO.setPreferredSize(new java.awt.Dimension(79, 74));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PNL_TELA.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        PNL_DESCRICAO.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        LBL_EMAIL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBL_EMAIL.setText("EMAIL:");

        LBL_SENHA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBL_SENHA.setText("SENHA:");

        BTN_LOGIN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_LOGIN.setText("LOGIN");
        BTN_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LOGINActionPerformed(evt);
            }
        });

        LBL_BRASAO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/urnaeletronica/imagens/BrasaoJusticaEleitoral.png"))); // NOI18N
        LBL_BRASAO1.setMaximumSize(new java.awt.Dimension(79, 74));
        LBL_BRASAO1.setMinimumSize(new java.awt.Dimension(79, 74));
        LBL_BRASAO1.setPreferredSize(new java.awt.Dimension(79, 74));

        BTN_AJUDA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTN_AJUDA.setForeground(new java.awt.Color(255, 0, 0));
        BTN_AJUDA.setText("?");
        BTN_AJUDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AJUDAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNL_DESCRICAOLayout = new javax.swing.GroupLayout(PNL_DESCRICAO);
        PNL_DESCRICAO.setLayout(PNL_DESCRICAOLayout);
        PNL_DESCRICAOLayout.setHorizontalGroup(
            PNL_DESCRICAOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_DESCRICAOLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(BTN_LOGIN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_DESCRICAOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBL_BRASAO1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PNL_DESCRICAOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_DESCRICAOLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(PNL_DESCRICAOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBL_SENHA)
                            .addComponent(PSW_SENHA, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122))
                    .addGroup(PNL_DESCRICAOLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PNL_DESCRICAOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_EMAIL))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_DESCRICAOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_AJUDA))
        );
        PNL_DESCRICAOLayout.setVerticalGroup(
            PNL_DESCRICAOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_DESCRICAOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PNL_DESCRICAOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LBL_BRASAO1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PNL_DESCRICAOLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(LBL_EMAIL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXT_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBL_SENHA)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PSW_SENHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(BTN_LOGIN)
                .addGap(3, 3, 3)
                .addComponent(BTN_AJUDA))
        );

        javax.swing.GroupLayout PNL_TELALayout = new javax.swing.GroupLayout(PNL_TELA);
        PNL_TELA.setLayout(PNL_TELALayout);
        PNL_TELALayout.setHorizontalGroup(
            PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_TELALayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(PNL_DESCRICAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        PNL_TELALayout.setVerticalGroup(
            PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_TELALayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(PNL_DESCRICAO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNL_TELA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNL_TELA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_AJUDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AJUDAActionPerformed
        JOptionPane.showMessageDialog(null, "Digite o email e senha para iniciar a urna!");
    }//GEN-LAST:event_BTN_AJUDAActionPerformed

    private void BTN_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LOGINActionPerformed
        String nome = "";
        String email = TXT_EMAIL.getText();
        String Senha = "";
        String senhaTela = PSW_SENHA.getText();

        String sql = "select * from fiscal_urna where FIS_LOGIN = ?";

        String url = "jdbc:mysql://127.0.0.1:3306/eleicao";
        String user = "root";
        String senha = "shieldcorrupted";

        try{
            Connection conexao = DriverManager.getConnection(url, user, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            comando.setString(1, email);
            ResultSet busca = comando.executeQuery();

            if(busca.next()==true){
                Senha = busca.getString("FIS_SENHA");
                if(Senha.equals(senhaTela)){
                    nome = busca.getString("FIS_NOME");
                    JOptionPane.showMessageDialog(null, "Acesso concedido!"
                            + "\nBem Vindo "+nome);
                 MenuUrna tela = new MenuUrna();
                 tela.setVisible(true);
                    dispose();
                }
            }else{
                JOptionPane.showMessageDialog(null, "LOGIN INCORRETO!");
                TXT_EMAIL.setText(null);
                PSW_SENHA.setText(null);
            }
            comando.close();
            conexao.close();

        }catch(SQLException erro){
            erro.printStackTrace();
        }
    }//GEN-LAST:event_BTN_LOGINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUrna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_AJUDA;
    private javax.swing.JButton BTN_LOGIN;
    private javax.swing.JLabel LBL_BRASAO;
    private javax.swing.JLabel LBL_BRASAO1;
    private javax.swing.JLabel LBL_EMAIL;
    private javax.swing.JLabel LBL_SENHA;
    private javax.swing.JPanel PNL_DESCRICAO;
    private javax.swing.JPanel PNL_TELA;
    private javax.swing.JPasswordField PSW_SENHA;
    private javax.swing.JTextField TXT_EMAIL;
    // End of variables declaration//GEN-END:variables
}
