/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package urnaeletronica;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.text.Document;
import javax.swing.text.PlainDocument;

/**
 *
 * @author MARCELO
 */
public class TelaVotacao extends javax.swing.JFrame {

    public void ImagemEleitor(){
        File img = new File("C:\\Users\\Mauricio\\Pictures\\Urna\\UP.png");
        ImageIcon Eleitor = new ImageIcon(img.getPath());
        LBL_FOTO.setIcon(Eleitor);
        
    }
    /**
     * Creates new form TelaInicializacao
     */
    public TelaVotacao() {
        initComponents();
        TXT_NUM1.setEditable(false);
        TXT_NUM2.setEditable(false);
        TXT_NUM3.setEditable(false);
        TXT_NUM4.setEditable(false);
        TXT_NUM5.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNL_TOTAL = new javax.swing.JPanel();
        PNL_DIGITOS = new javax.swing.JPanel();
        SPD_DIGITOS = new javax.swing.JSeparator();
        LBL_BRASAO = new javax.swing.JLabel();
        LBL_JUSTICA = new javax.swing.JLabel();
        LBL_ELEITORAL = new javax.swing.JLabel();
        BTN_1 = new javax.swing.JButton();
        BTN_2 = new javax.swing.JButton();
        BTN_3 = new javax.swing.JButton();
        BTN_6 = new javax.swing.JButton();
        BTN_5 = new javax.swing.JButton();
        BTN_4 = new javax.swing.JButton();
        BTN_9 = new javax.swing.JButton();
        BTN_8 = new javax.swing.JButton();
        BTN_7 = new javax.swing.JButton();
        BTN_0 = new javax.swing.JButton();
        BTN_BRANCO = new javax.swing.JButton();
        BTN_CORRIGE = new javax.swing.JButton();
        BTN_CONFIRMA = new javax.swing.JButton();
        PNL_TELA = new javax.swing.JPanel();
        LBL_FOTO = new javax.swing.JLabel();
        LBL_SEUVOTO = new javax.swing.JLabel();
        LBL_CARGO = new javax.swing.JLabel();
        LBL_NUMERO = new javax.swing.JLabel();
        TXT_NUM1 = new javax.swing.JTextField();
        TXT_NUM2 = new javax.swing.JTextField();
        TXT_NUM3 = new javax.swing.JTextField();
        TXT_NUM4 = new javax.swing.JTextField();
        TXT_NUM5 = new javax.swing.JTextField();
        LBL_NOMECANDIDATO = new javax.swing.JLabel();
        LBL_SIGLAPARTIDO = new javax.swing.JLabel();
        LBL_NOME = new javax.swing.JLabel();
        LBL_PARTIDO = new javax.swing.JLabel();
        LBL_APERTE = new javax.swing.JLabel();
        LBL_VERDE = new javax.swing.JLabel();
        LBL_PARA1 = new javax.swing.JLabel();
        LBL_CONFIRMAR = new javax.swing.JLabel();
        LBL_LARANJA = new javax.swing.JLabel();
        LBL_CORRIGIR = new javax.swing.JLabel();
        LBL_PARA2 = new javax.swing.JLabel();
        LBL_FOTOVICE = new javax.swing.JLabel();
        LBL_VICE = new javax.swing.JLabel();
        LBL_NOMECANDIDATO1 = new javax.swing.JLabel();
        SPD_CONFIRMACAO = new javax.swing.JSeparator();
        LBL_VOTOBRANCONULO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PNL_TOTAL.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        PNL_DIGITOS.setBackground(new java.awt.Color(153, 153, 153));
        PNL_DIGITOS.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        LBL_BRASAO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/urnaeletronica/imagens/BrasaoJusticaEleitoral.png"))); // NOI18N
        LBL_BRASAO.setMaximumSize(new java.awt.Dimension(79, 74));
        LBL_BRASAO.setMinimumSize(new java.awt.Dimension(79, 74));
        LBL_BRASAO.setPreferredSize(new java.awt.Dimension(79, 74));

        LBL_JUSTICA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LBL_JUSTICA.setText("JUSTIÇA");

        LBL_ELEITORAL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LBL_ELEITORAL.setText("ELEITORAL");

        BTN_1.setBackground(new java.awt.Color(0, 0, 0));
        BTN_1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        BTN_1.setForeground(new java.awt.Color(255, 255, 255));
        BTN_1.setText("1");
        BTN_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_1ActionPerformed(evt);
            }
        });

        BTN_2.setBackground(new java.awt.Color(0, 0, 0));
        BTN_2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        BTN_2.setForeground(new java.awt.Color(255, 255, 255));
        BTN_2.setText("2");
        BTN_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_2ActionPerformed(evt);
            }
        });

        BTN_3.setBackground(new java.awt.Color(0, 0, 0));
        BTN_3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        BTN_3.setForeground(new java.awt.Color(255, 255, 255));
        BTN_3.setText("3");
        BTN_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_3ActionPerformed(evt);
            }
        });

        BTN_6.setBackground(new java.awt.Color(0, 0, 0));
        BTN_6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        BTN_6.setForeground(new java.awt.Color(255, 255, 255));
        BTN_6.setText("6");
        BTN_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_6ActionPerformed(evt);
            }
        });

        BTN_5.setBackground(new java.awt.Color(0, 0, 0));
        BTN_5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        BTN_5.setForeground(new java.awt.Color(255, 255, 255));
        BTN_5.setText("5");
        BTN_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_5ActionPerformed(evt);
            }
        });

        BTN_4.setBackground(new java.awt.Color(0, 0, 0));
        BTN_4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        BTN_4.setForeground(new java.awt.Color(255, 255, 255));
        BTN_4.setText("4");
        BTN_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_4ActionPerformed(evt);
            }
        });

        BTN_9.setBackground(new java.awt.Color(0, 0, 0));
        BTN_9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        BTN_9.setForeground(new java.awt.Color(255, 255, 255));
        BTN_9.setText("9");
        BTN_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_9ActionPerformed(evt);
            }
        });

        BTN_8.setBackground(new java.awt.Color(0, 0, 0));
        BTN_8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        BTN_8.setForeground(new java.awt.Color(255, 255, 255));
        BTN_8.setText("8");
        BTN_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_8ActionPerformed(evt);
            }
        });

        BTN_7.setBackground(new java.awt.Color(0, 0, 0));
        BTN_7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        BTN_7.setForeground(new java.awt.Color(255, 255, 255));
        BTN_7.setText("7");
        BTN_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_7ActionPerformed(evt);
            }
        });

        BTN_0.setBackground(new java.awt.Color(0, 0, 0));
        BTN_0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        BTN_0.setForeground(new java.awt.Color(255, 255, 255));
        BTN_0.setText("0");
        BTN_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_0ActionPerformed(evt);
            }
        });

        BTN_BRANCO.setBackground(new java.awt.Color(255, 255, 255));
        BTN_BRANCO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_BRANCO.setText("BRANCO");
        BTN_BRANCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BRANCOActionPerformed(evt);
            }
        });

        BTN_CORRIGE.setBackground(new java.awt.Color(255, 51, 0));
        BTN_CORRIGE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_CORRIGE.setText("CORRIGE");
        BTN_CORRIGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CORRIGEActionPerformed(evt);
            }
        });

        BTN_CONFIRMA.setBackground(new java.awt.Color(0, 153, 0));
        BTN_CONFIRMA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_CONFIRMA.setText("CONFIRMA");
        BTN_CONFIRMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CONFIRMAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNL_DIGITOSLayout = new javax.swing.GroupLayout(PNL_DIGITOS);
        PNL_DIGITOS.setLayout(PNL_DIGITOSLayout);
        PNL_DIGITOSLayout.setHorizontalGroup(
            PNL_DIGITOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SPD_DIGITOS, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_DIGITOSLayout.createSequentialGroup()
                .addGroup(PNL_DIGITOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PNL_DIGITOSLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBL_BRASAO, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PNL_DIGITOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBL_ELEITORAL, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_JUSTICA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addGroup(PNL_DIGITOSLayout.createSequentialGroup()
                        .addGroup(PNL_DIGITOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_DIGITOSLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(PNL_DIGITOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BTN_1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(BTN_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BTN_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(PNL_DIGITOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BTN_2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTN_5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTN_8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PNL_DIGITOSLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTN_0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(PNL_DIGITOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PNL_DIGITOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BTN_6, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addComponent(BTN_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(30, 30, 30))
            .addGroup(PNL_DIGITOSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTN_BRANCO)
                .addGap(18, 18, 18)
                .addComponent(BTN_CORRIGE, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BTN_CONFIRMA)
                .addContainerGap())
        );
        PNL_DIGITOSLayout.setVerticalGroup(
            PNL_DIGITOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_DIGITOSLayout.createSequentialGroup()
                .addGroup(PNL_DIGITOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_DIGITOSLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(LBL_BRASAO, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PNL_DIGITOSLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(LBL_JUSTICA, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBL_ELEITORAL, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPD_DIGITOS, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PNL_DIGITOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PNL_DIGITOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PNL_DIGITOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BTN_0, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(PNL_DIGITOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_DIGITOSLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PNL_DIGITOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN_BRANCO, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_CORRIGE, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BTN_CONFIRMA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PNL_TELA.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        LBL_FOTO.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LBL_FOTO.setMaximumSize(new java.awt.Dimension(110, 110));
        LBL_FOTO.setMinimumSize(new java.awt.Dimension(110, 110));

        LBL_SEUVOTO.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_SEUVOTO.setText("SEU VOTO PARA");

        LBL_CARGO.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LBL_CARGO.setText("DEPUTADO ESTADUAL (a)");

        LBL_NUMERO.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_NUMERO.setText("NÚMERO:");

        TXT_NUM1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        TXT_NUM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_NUM1ActionPerformed(evt);
            }
        });

        TXT_NUM2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N

        TXT_NUM3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N

        TXT_NUM4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N

        TXT_NUM5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N

        LBL_NOMECANDIDATO.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LBL_NOMECANDIDATO.setText("LULA");

        LBL_SIGLAPARTIDO.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LBL_SIGLAPARTIDO.setText("PT");

        LBL_NOME.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_NOME.setText("NOME:");

        LBL_PARTIDO.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_PARTIDO.setText("PARTIDO:");

        LBL_APERTE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_APERTE.setText("Aperte a tecla");

        LBL_VERDE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LBL_VERDE.setForeground(new java.awt.Color(0, 153, 0));
        LBL_VERDE.setText("VERDE");

        LBL_PARA1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_PARA1.setText("para");

        LBL_CONFIRMAR.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LBL_CONFIRMAR.setForeground(new java.awt.Color(0, 153, 0));
        LBL_CONFIRMAR.setText("CONFIRMAR");

        LBL_LARANJA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LBL_LARANJA.setForeground(new java.awt.Color(255, 51, 0));
        LBL_LARANJA.setText("LARANJA");

        LBL_CORRIGIR.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LBL_CORRIGIR.setForeground(new java.awt.Color(255, 51, 0));
        LBL_CORRIGIR.setText("CORRIGIR");

        LBL_PARA2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_PARA2.setText("para");

        LBL_VICE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_VICE.setText("VICE ou SUPLENTE:");

        LBL_NOMECANDIDATO1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LBL_NOMECANDIDATO1.setText("DILMA");

        LBL_VOTOBRANCONULO.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        javax.swing.GroupLayout PNL_TELALayout = new javax.swing.GroupLayout(PNL_TELA);
        PNL_TELA.setLayout(PNL_TELALayout);
        PNL_TELALayout.setHorizontalGroup(
            PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_TELALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBL_VOTOBRANCONULO, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
            .addGroup(PNL_TELALayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_TELALayout.createSequentialGroup()
                        .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_TELALayout.createSequentialGroup()
                                .addComponent(LBL_VERDE, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBL_PARA1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBL_CONFIRMAR, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PNL_TELALayout.createSequentialGroup()
                                .addComponent(LBL_LARANJA, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBL_PARA2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBL_CORRIGIR, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LBL_APERTE, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 365, Short.MAX_VALUE))
                    .addGroup(PNL_TELALayout.createSequentialGroup()
                        .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_TELALayout.createSequentialGroup()
                                .addComponent(LBL_NUMERO)
                                .addGap(18, 18, 18)
                                .addComponent(TXT_NUM1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXT_NUM2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXT_NUM3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXT_NUM4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXT_NUM5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PNL_TELALayout.createSequentialGroup()
                                .addComponent(LBL_PARTIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBL_SIGLAPARTIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PNL_TELALayout.createSequentialGroup()
                                .addComponent(LBL_NOME, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBL_NOMECANDIDATO, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PNL_TELALayout.createSequentialGroup()
                                .addComponent(LBL_VICE, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBL_NOMECANDIDATO1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LBL_CARGO, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_SEUVOTO, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LBL_FOTOVICE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_FOTO, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
            .addGroup(PNL_TELALayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(SPD_CONFIRMACAO, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PNL_TELALayout.setVerticalGroup(
            PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_TELALayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(LBL_SEUVOTO)
                .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PNL_TELALayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(LBL_FOTO, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PNL_TELALayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBL_CARGO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LBL_NUMERO)
                            .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TXT_NUM1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TXT_NUM2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TXT_NUM3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TXT_NUM4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TXT_NUM5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PNL_TELALayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(LBL_FOTOVICE, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PNL_TELALayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBL_NOMECANDIDATO, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_NOME, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBL_SIGLAPARTIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_PARTIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_VICE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_NOMECANDIDATO1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBL_VOTOBRANCONULO, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPD_CONFIRMACAO, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBL_APERTE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LBL_VERDE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LBL_PARA1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LBL_CONFIRMAR, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_CORRIGIR, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PNL_TELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LBL_LARANJA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LBL_PARA2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout PNL_TOTALLayout = new javax.swing.GroupLayout(PNL_TOTAL);
        PNL_TOTAL.setLayout(PNL_TOTALLayout);
        PNL_TOTALLayout.setHorizontalGroup(
            PNL_TOTALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_TOTALLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PNL_TELA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(PNL_DIGITOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        PNL_TOTALLayout.setVerticalGroup(
            PNL_TOTALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_TOTALLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(PNL_TOTALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_TOTALLayout.createSequentialGroup()
                        .addComponent(PNL_TELA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_TOTALLayout.createSequentialGroup()
                        .addComponent(PNL_DIGITOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNL_TOTAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNL_TOTAL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_CONFIRMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CONFIRMAActionPerformed
        LBL_NUMERO.setText("NÚMERO:");
        TXT_NUM1.setVisible(true);
        TXT_NUM2.setVisible(true);
        TXT_NUM3.setVisible(true);
        TXT_NUM4.setVisible(true);
        TXT_NUM5.setVisible(true);
        
        if(LBL_CARGO.getText().equals("DEPUTADO ESTADUAL (a)") && LBL_VOTOBRANCONULO.getText().equals("VOTO EM BRANCO")){
            LBL_VOTOBRANCONULO.setText(null);
            TXT_NUM5.setVisible(false);
            LBL_CARGO.setText("DEPUTADO FEDERAL (a)");
        }else if(LBL_CARGO.getText().equals("DEPUTADO FEDERAL (a)") && LBL_VOTOBRANCONULO.getText().equals("VOTO EM BRANCO")){
            LBL_VOTOBRANCONULO.setText(null);
            TXT_NUM4.setVisible(false);
            LBL_CARGO.setText("SENADOR (a)");
        }else if(LBL_CARGO.getText().equals("SENADOR (a)") && LBL_VOTOBRANCONULO.getText().equals("VOTO EM BRANCO")){
            LBL_VOTOBRANCONULO.setText(null);
            TXT_NUM3.setVisible(false);
            LBL_CARGO.setText("GOVERNADOR (a)");
        }else if(LBL_CARGO.getText().equals("GOVERNADOR (a)") && LBL_VOTOBRANCONULO.getText().equals("VOTO EM BRANCO")){
            LBL_VOTOBRANCONULO.setText(null);
            LBL_CARGO.setText("PRESIDENTE (a)");
        }

        //ImagemEleitor();
        //TXT_NUM5.setVisible(false);     
    }//GEN-LAST:event_BTN_CONFIRMAActionPerformed

    private void BTN_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_1ActionPerformed
        if(LBL_CARGO.getText().equals("DEPUTADO ESTADUAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("1");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("1");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("1");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("1");
            }else if(TXT_NUM5.getText().equals("")){
                TXT_NUM5.setText("1");
            } 
        }else if(LBL_CARGO.getText().equals("DEPUTADO FEDERAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("1");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("1");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("1");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("1");
            }
        }else if(LBL_CARGO.getText().equals("SENADOR (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("1");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("1");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("1");
            }
        }else if(LBL_CARGO.getText().equals("GOVERNADOR (a)")||LBL_CARGO.getText().equals("PRESIDENTE (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("1");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("1");
            }
        }
    }//GEN-LAST:event_BTN_1ActionPerformed

    private void TXT_NUM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_NUM1ActionPerformed

    }//GEN-LAST:event_TXT_NUM1ActionPerformed

    private void BTN_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_2ActionPerformed
         if(LBL_CARGO.getText().equals("DEPUTADO ESTADUAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("2");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("2");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("2");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("2");
            }else if(TXT_NUM5.getText().equals("")){
                TXT_NUM5.setText("2");
            } 
        }else if(LBL_CARGO.getText().equals("DEPUTADO FEDERAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("2");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("2");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("2");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("2");
            }
        }else if(LBL_CARGO.getText().equals("SENADOR (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("2");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("2");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("2");
            }
        }else if(LBL_CARGO.getText().equals("GOVERNADOR (a)")||LBL_CARGO.getText().equals("PRESIDENTE (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("2");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("2");
            }
        }
    }//GEN-LAST:event_BTN_2ActionPerformed

    private void BTN_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_3ActionPerformed
         if(LBL_CARGO.getText().equals("DEPUTADO ESTADUAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("3");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("3");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("3");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("3");
            }else if(TXT_NUM5.getText().equals("")){
                TXT_NUM5.setText("3");
            } 
        }else if(LBL_CARGO.getText().equals("DEPUTADO FEDERAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("3");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("3");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("3");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("3");
            }
        }else if(LBL_CARGO.getText().equals("SENADOR (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("3");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("3");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("3");
            }
        }else if(LBL_CARGO.getText().equals("GOVERNADOR (a)")||LBL_CARGO.getText().equals("PRESIDENTE (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("3");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("3");
            }
        }
    }//GEN-LAST:event_BTN_3ActionPerformed

    private void BTN_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_4ActionPerformed
             if(LBL_CARGO.getText().equals("DEPUTADO ESTADUAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("4");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("4");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("4");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("4");
            }else if(TXT_NUM5.getText().equals("")){
                TXT_NUM5.setText("4");
            } 
        }else if(LBL_CARGO.getText().equals("DEPUTADO FEDERAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("4");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("4");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("4");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("4");
            }
        }else if(LBL_CARGO.getText().equals("SENADOR (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("4");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("4");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("4");
            }
        }else if(LBL_CARGO.getText().equals("GOVERNADOR (a)")||LBL_CARGO.getText().equals("PRESIDENTE (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("4");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("4");
            }
        }
    }//GEN-LAST:event_BTN_4ActionPerformed

    private void BTN_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_5ActionPerformed
         if(LBL_CARGO.getText().equals("DEPUTADO ESTADUAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("5");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("5");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("5");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("5");
            }else if(TXT_NUM5.getText().equals("")){
                TXT_NUM5.setText("5");
            } 
        }else if(LBL_CARGO.getText().equals("DEPUTADO FEDERAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("5");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("5");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("5");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("5");
            }
        }else if(LBL_CARGO.getText().equals("SENADOR (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("5");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("5");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("5");
            }
        }else if(LBL_CARGO.getText().equals("GOVERNADOR (a)")||LBL_CARGO.getText().equals("PRESIDENTE (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("5");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("5");
            }
        }
    }//GEN-LAST:event_BTN_5ActionPerformed

    private void BTN_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_6ActionPerformed
             if(LBL_CARGO.getText().equals("DEPUTADO ESTADUAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("6");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("6");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("6");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("6");
            }else if(TXT_NUM5.getText().equals("")){
                TXT_NUM5.setText("6");
            } 
        }else if(LBL_CARGO.getText().equals("DEPUTADO FEDERAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("6");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("6");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("6");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("6");
            }
        }else if(LBL_CARGO.getText().equals("SENADOR (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("6");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("6");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("6");
            }
        }else if(LBL_CARGO.getText().equals("GOVERNADOR (a)")||LBL_CARGO.getText().equals("PRESIDENTE (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("6");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("6");
            }
        }
    }//GEN-LAST:event_BTN_6ActionPerformed

    private void BTN_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_7ActionPerformed
         if(LBL_CARGO.getText().equals("DEPUTADO ESTADUAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("7");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("7");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("7");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("7");
            }else if(TXT_NUM5.getText().equals("")){
                TXT_NUM5.setText("7");
            } 
        }else if(LBL_CARGO.getText().equals("DEPUTADO FEDERAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("7");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("7");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("7");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("7");
            }
        }else if(LBL_CARGO.getText().equals("SENADOR (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("7");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("7");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("7");
            }
        }else if(LBL_CARGO.getText().equals("GOVERNADOR (a)")||LBL_CARGO.getText().equals("PRESIDENTE (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("7");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("7");
            }
        }
    }//GEN-LAST:event_BTN_7ActionPerformed

    private void BTN_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_8ActionPerformed
         if(LBL_CARGO.getText().equals("DEPUTADO ESTADUAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("8");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("8");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("8");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("8");
            }else if(TXT_NUM5.getText().equals("")){
                TXT_NUM5.setText("8");
            } 
        }else if(LBL_CARGO.getText().equals("DEPUTADO FEDERAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("8");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("8");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("8");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("8");
            }
        }else if(LBL_CARGO.getText().equals("SENADOR (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("8");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("8");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("8");
            }
        }else if(LBL_CARGO.getText().equals("GOVERNADOR (a)")||LBL_CARGO.getText().equals("PRESIDENTE (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("8");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("8");
            }
        }
    }//GEN-LAST:event_BTN_8ActionPerformed

    private void BTN_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_9ActionPerformed
         if(LBL_CARGO.getText().equals("DEPUTADO ESTADUAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("9");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("9");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("9");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("9");
            }else if(TXT_NUM5.getText().equals("")){
                TXT_NUM5.setText("9");
            } 
        }else if(LBL_CARGO.getText().equals("DEPUTADO FEDERAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("9");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("9");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("9");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("9");
            }
        }else if(LBL_CARGO.getText().equals("SENADOR (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("9");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("9");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("9");
            }
        }else if(LBL_CARGO.getText().equals("GOVERNADOR (a)")||LBL_CARGO.getText().equals("PRESIDENTE (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("9");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("9");
            }
        }
    }//GEN-LAST:event_BTN_9ActionPerformed

    private void BTN_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_0ActionPerformed
         if(LBL_CARGO.getText().equals("DEPUTADO ESTADUAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("0");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("0");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("0");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("0");
            }else if(TXT_NUM5.getText().equals("")){
                TXT_NUM5.setText("0");
            } 
        }else if(LBL_CARGO.getText().equals("DEPUTADO FEDERAL (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("0");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("0");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("0");
            }else if(TXT_NUM4.getText().equals("")){
                TXT_NUM4.setText("0");
            }
        }else if(LBL_CARGO.getText().equals("SENADOR (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("0");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("0");
            }else if(TXT_NUM3.getText().equals("")){
                TXT_NUM3.setText("0");
            }
        }else if(LBL_CARGO.getText().equals("GOVERNADOR (a)")||LBL_CARGO.getText().equals("PRESIDENTE (a)")){
            if(TXT_NUM1.getText().equals("")){
                TXT_NUM1.setText("0");
            }else if(TXT_NUM2.getText().equals("")){
                TXT_NUM2.setText("0");
            }
        }
    }//GEN-LAST:event_BTN_0ActionPerformed

    private void BTN_CORRIGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CORRIGEActionPerformed
        if(LBL_VOTOBRANCONULO.getText().equals("VOTO EM BRANCO")){
            LBL_NUMERO.setText("NÚMERO:");
            TXT_NUM1.setVisible(true);
            TXT_NUM2.setVisible(true);
            TXT_NUM3.setVisible(true);
            TXT_NUM4.setVisible(true);
            TXT_NUM5.setVisible(true);
            LBL_VOTOBRANCONULO.setText(null);
        }else{
            TXT_NUM1.setText(null);
            TXT_NUM2.setText(null);
            TXT_NUM3.setText(null);
            TXT_NUM4.setText(null);
            TXT_NUM5.setText(null);

            LBL_NOME.setText(null);
            LBL_NOMECANDIDATO.setText(null);
            LBL_NOMECANDIDATO1.setText(null);
            LBL_PARTIDO.setText(null);
            LBL_SIGLAPARTIDO.setText(null);
            LBL_VICE.setText(null);
        }
    }//GEN-LAST:event_BTN_CORRIGEActionPerformed

    private void BTN_BRANCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BRANCOActionPerformed
        TXT_NUM1.setText(null);
        TXT_NUM2.setText(null);
        TXT_NUM3.setText(null);
        TXT_NUM4.setText(null);
        TXT_NUM5.setText(null);
        
        TXT_NUM1.setVisible(false);
        TXT_NUM2.setVisible(false);
        TXT_NUM3.setVisible(false);
        TXT_NUM4.setVisible(false);
        TXT_NUM5.setVisible(false);
        
        LBL_NUMERO.setText(null);
        LBL_NOME.setText(null);
        LBL_NOMECANDIDATO.setText(null);
        LBL_NOMECANDIDATO1.setText(null);
        LBL_PARTIDO.setText(null);
        LBL_SIGLAPARTIDO.setText(null);
        LBL_VICE.setText(null);
        
        LBL_VOTOBRANCONULO.setText("VOTO EM BRANCO");
    }//GEN-LAST:event_BTN_BRANCOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVotacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_0;
    private javax.swing.JButton BTN_1;
    private javax.swing.JButton BTN_2;
    private javax.swing.JButton BTN_3;
    private javax.swing.JButton BTN_4;
    private javax.swing.JButton BTN_5;
    private javax.swing.JButton BTN_6;
    private javax.swing.JButton BTN_7;
    private javax.swing.JButton BTN_8;
    private javax.swing.JButton BTN_9;
    private javax.swing.JButton BTN_BRANCO;
    private javax.swing.JButton BTN_CONFIRMA;
    private javax.swing.JButton BTN_CORRIGE;
    private javax.swing.JLabel LBL_APERTE;
    private javax.swing.JLabel LBL_BRASAO;
    private javax.swing.JLabel LBL_CARGO;
    private javax.swing.JLabel LBL_CONFIRMAR;
    private javax.swing.JLabel LBL_CORRIGIR;
    private javax.swing.JLabel LBL_ELEITORAL;
    private javax.swing.JLabel LBL_FOTO;
    private javax.swing.JLabel LBL_FOTOVICE;
    private javax.swing.JLabel LBL_JUSTICA;
    private javax.swing.JLabel LBL_LARANJA;
    private javax.swing.JLabel LBL_NOME;
    private javax.swing.JLabel LBL_NOMECANDIDATO;
    private javax.swing.JLabel LBL_NOMECANDIDATO1;
    private javax.swing.JLabel LBL_NUMERO;
    private javax.swing.JLabel LBL_PARA1;
    private javax.swing.JLabel LBL_PARA2;
    private javax.swing.JLabel LBL_PARTIDO;
    private javax.swing.JLabel LBL_SEUVOTO;
    private javax.swing.JLabel LBL_SIGLAPARTIDO;
    private javax.swing.JLabel LBL_VERDE;
    private javax.swing.JLabel LBL_VICE;
    private javax.swing.JLabel LBL_VOTOBRANCONULO;
    private javax.swing.JPanel PNL_DIGITOS;
    private javax.swing.JPanel PNL_TELA;
    private javax.swing.JPanel PNL_TOTAL;
    private javax.swing.JSeparator SPD_CONFIRMACAO;
    private javax.swing.JSeparator SPD_DIGITOS;
    private javax.swing.JTextField TXT_NUM1;
    private javax.swing.JTextField TXT_NUM2;
    private javax.swing.JTextField TXT_NUM3;
    private javax.swing.JTextField TXT_NUM4;
    private javax.swing.JTextField TXT_NUM5;
    // End of variables declaration//GEN-END:variables
}
